name: "test"

on:
  push:
    tags:
    - "v*"
  pull_request:
    tags:
    - "v*"

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        ENVATO_USERNAME: ${{ secrets.ENVATO_USERNAME }}
        ENVATO_PERSONAL_TOKEN: ${{ secrets.ENVATO_PERSONAL_TOKEN }}
        ZIP_FILES: |
          ./README.md
          ./package.json
